%global debug_package %{nil}

%global pkgname v4l2loopback

Name:     %{pkgname}-dkms
Version:  0.12.7
Release:  2%{?dist}
Summary:  Kernel module to create Video4Linux loopback devices (DKMS)
Group:    System Environment/Kernel
License:  GPLv2
URL:      https://github.com/umlaeute/v4l2loopback
Source0:  https://github.com/umlaeute/v4l2loopback/archive/v%{version}.tar.gz

BuildArch: noarch

Requires:       kernel-devel
Provides:       %{name}-kmod = %{version}
Requires:       dkms >= 2.2

%description
This module and associated tools can create "virtual video devices" accessible
through the Video4Linux API.
Normal (v4l2) applications will read these devices as if they were ordinary
video devices, but the video will not be read from e.g. a capture card but
instead generated by another application.

This package contains the module source and DKMS configuration to build thev
v4l2loopback kernel module.

%post
%{_prefix}/lib/dkms/common.postinst %{pkgname} %{version}

%preun
if [ $1 -ne 1 ]; then
    dkms remove -m %{pkgname} -v %{version} --all --rpm_safe_upgrade || :
fi

%prep
%autosetup -c %{pkgname}-%{version}

%build
# v4l2loopback is a shell script

%install
mkdir -p "${RPM_BUILD_ROOT}%{_usrsrc}"
cp -r %{pkgname}-%{version} "${RPM_BUILD_ROOT}%{_usrsrc}/"

%files
%config(noreplace)%{_usrsrc}/%{pkgname}-%{version}/dkms.conf
%doc %{_usrsrc}/%{pkgname}-%{version}/AUTHORS
%doc %{_usrsrc}/%{pkgname}-%{version}/COPYING
%doc %{_usrsrc}/%{pkgname}-%{version}/NEWS
%doc %{_usrsrc}/%{pkgname}-%{version}/README.md
%doc %{_usrsrc}/%{pkgname}-%{version}/TODO
%doc %{_usrsrc}/%{pkgname}-%{version}/doc
%doc %{_usrsrc}/%{pkgname}-%{version}/examples
%doc %{_usrsrc}/%{pkgname}-%{version}/man
%{_usrsrc}/%{pkgname}-%{version}

%changelog
* Sat May 30 2020 Jan Drögehoff <sentrycraft123@gmail.com> - 0.12.5-2
- add kernel-devel requirement

* Fri May 01 2020 Jan Drögehoff <sentrycraft123@gmail.com> - 0.12.5-1
- Bump to version 0.12.5

* Fri Nov 01 2019 Jan Drögehoff <jandroegehoff@gmail.com - 0.12.2
- Update to latest version
- fix copr build

* Thu Jun 23 2016 Daniel Miranda <danielkza2@gmail.com> - 0.9.1-2
- Remove unneeded build dependencies
- Fix DKMS trigger on package update

* Wed Jun 22 2016 Daniel Miranda <danielkza2@gmail.com> - 0.9.1-1
- Initial release

